### ISSUE TITLE
Wrong default INTERFACE

### ISSUE THREAD

**Issue by ldidry** [tiredofit/docker-collabora-online#26]
### Summary

The README says that the default for `INTERFACE` is `notebookbar` but `install/assets/defaults/10-coolwsd` set it to `classic` on its [line 42](https://github.com/tiredofit/docker-collabora-online/blob/main/install/assets/defaults/10-coolwsd#L42).

### Steps to reproduce

Don’t set `INTERFACE` env var.

### What is the expected *correct* behavior?

README and `install/assets/defaults/10-coolwsd` should have the same default value.

**Comment by tiredofit** [comment]
Thanks for the feedback - this has been resolved with https://github.com/tiredofit/docker-collabora-online/commit/99d2163aae6c5f4c1aae4b8ffc77d47e451ac775 - It really should be `notebookbar`.
