### ISSUE TITLE
Crash at startup after latest release

### ISSUE THREAD

**Issue by frosenek** [tiredofit/docker-collabora-online#33]
### Summary

Container crashes at startup because of XML-parsing exception.

### Steps to reproduce

Start container.

### What is the expected *correct* behavior?

No crash at startup.

### Relevant logs and/or screenshots

2023-03-28.07:05:12 [STARTING] ** [collabora-online] [50] Starting Libreoffice Online Web Services daemon
Failed to initialize COOLWSD: SAXParseException: Tag mismatch in '/etc/coolwsd/coolwsd.xml', line 63 column 150
-04264 2023-03-28 07:05:12.132638 +0000 [ coolwsd ] FTL  Failed to initialize COOLWSD: SAXParseException: Tag mismatch in '/etc/coolwsd/coolwsd.xml', line 63 column 150| wsd/COOLWSD.hpp:503
SAXParseException: Tag mismatch in '/etc/coolwsd/coolwsd.xml', line 63 column 150
2023-03-28.07:05:13 [ERROR] ** [collabora-online] POTENTIAL RUNWAY DETECTECTED: Disabling 10-coolwsd service because it has tried restarting '50' times

### Stack

version: '3'

services:
  collabora:
    image: tiredofit/collabora-online:latest
    container_name: collabora-online
    networks:
      default:
        ipv4_address: 172.20.0.6
    cap_add:
      - MKNOD
    environment:
      - "ADMIN_USER=redacted"
      - "ADMIN_PASS=redacted"
      - "LOG_LEVEL=warning"
      - "DICTIONARIES=de_DE en_GB en_US"
      - "HOSTNAME=redacted"
      - "ALLOWED_HOSTS=redacted"
      - ENABLE_TLS=FALSE
      - ENABLE_TLS_REVERSE_PROXY=TRUE
    volumes:
      - colla_logs:/logs
    ports:
      - "127.0.0.1:9980:9980"
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
networks:
  default:
    ipam:
      config:
        - subnet: "172.20.0.4/30" 
volumes:
  colla_logs:

- Image version / tag:  latest
- Host OS: debian 11

**Comment by tiredofit** [comment]
Would you mind getting me line 50 of your config file?
If you enter into the container even when it is not running COOL, you can type `sed -n '50p' /etc/cool/coolwsd.xml`.

**Comment by tiredofit** [comment]
Actually no worries. I have found it. I seem to have made a mess of this release. Fix incoming shortly.

**Comment by tiredofit** [comment]
`2.4.27` fixes the above and 3 other issues. It takes a long time to build so check in a few hours ?

**Comment by joergmschulz** [comment]
not really - the 2.4.27 on docker crashes as well - the version that runs perfectly is 2.4.29. Just compiled that version locally, runs fine. What happened to the build on docker?

**Comment by tiredofit** [comment]
Weird. Something is going wrong with my build system. To look into.

**Comment by tiredofit** [comment]
Should be back to normal now.. I see 2.4.29 and updated latest up on Hub.

**Comment by joergmschulz** [comment]
Replaced my local version with the docker version, confirm: all is ok. Suggestion: this issue can now be closed now.
