### ISSUE TITLE
Docker.io has old image

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-collabora-online#39]
The image :latest on docker.io still is the previous version - something in the build chain seems to have failed?

**Comment by tiredofit** [comment]
Let me look into. I build it manually and something might have glitched out. Github actions isn't powerful enough to build it as it uses something along the lines of 50gb when building...

**Comment by tiredofit** [comment]
Image should be up to date now!

**Comment by joergmschulz** [comment]
Indeed, thank you very much
