### ISSUE TITLE
versions after 24.04.4-1 don't start

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-collabora-online#43]
versions after 24.0.4.4-1, especially .4 and latest don't start.

Error message:
```Failed to initialize COOLWSD: File not found: /etc/coolwsd/certs/ca-chain.cert.pem| wsd/COOLWSD.hpp:522```
but the compose contains the variables:
```
      - ENABLE_TLS_CERT_GENERATE=FALSE
      - ENABLE_TLS=FALSE
      - ENABLE_TLS_REVERSE_PROXY=TRUE
```
adding
```
      - TLS_CA_FILENAME=fullchain.pem
      - TLS_CERT_FILENAME=cert.pem
      - TLS_KEY_FILENAME=privkey.pem
```
and mounting the volume: helps

**Comment by tiredofit** [comment]
Interesting - I will have to peek on my installs to see if I see similar. I am generally just running on autopilot on building these and making sure they continue building.
 Let me try to find some time this week.

**Comment by tiredofit** [comment]
https://github.com/tiredofit/docker-collabora-online/releases/tag/24.04.4-4.1 should get you going!

**Comment by joergmschulz** [comment]
sorry - no. While this version _starts_ , I cannot connect and don't see any error msgs yet. Will continue to investigate later.

**Comment by joergmschulz** [comment]
I can only guess. Below, there is the ssl section of [24.04.4-4.1] . The difference to the - working - version of [24.04.4-4] is that below, the paths are empty whereas previously there were entries even if unused.
But as opposed to previously, I don't see any error messages, neither in the browser console nor in the coolwsd log.

Giving up for today. 

```
 <ssl desc="SSL settings">
            <as_scheme type="bool" default="true" desc="When set we exclusively use the WOPI URI's scheme to enable SSL for storage">true</as_scheme>
            <enable type="bool" desc="If as_scheme is false or not set, this can be set to force SSL encryption between storage and coolwsd. When empty this defaults to following the ssl.enable setting"></enable>
            <cert_file_path desc="Path to the cert file. When empty this defaults to following the ssl.cert_file_path setting" relative="false"></cert_file_path>
            <key_file_path desc="Path to the key file. When empty this defaults to following the ssl.key_file_path settinge" relative="false"></key_file_path>
            <ca_file_path desc="Path to the ca file. When empty this defaults to following the ssl.ca_file_path setting" relative="false"></ca_file_path>
            <cipher_list desc="List of OpenSSL ciphers to accept. If empty the defaults are used. These can be overridden only if absolutely needed."></cipher_list>
        </ssl>
```

**Comment by joergmschulz** [comment]
using the most recent image helps

**Comment by tiredofit** [comment]
Excellnet. I think its in their upstream code issue. Thanks for circling back.

**Comment by joergmschulz** [comment]
I am thankful for your repositories! So the least I can do is find glitches and comment where useful. Greetings from the German Black Forest
